### ISSUE TITLE
Writing non-ASCII charcters in LINUX (UBUNTU 14.04LTS)

### ISSUE THREAD

**Issue by DrTK** [VincentToups/matlab-utils#1]
Hi, thanks for the good work with mksqlite. It really works great and fast. I love it!
Unfortunately, I encountered following problem when on Linux:

Whenever I try to write a `char(i)` with `i>127` to database, I get an error: `"can't copy string in getstring()"`. This concerns "Umlaute" (ä,ö,ü) or degree sign °, or other things I unfortunately need to write to database.

The following code works perfectly under Windows, but fails on Linux:

```
function sqlite_test
    testDB = 'test.sqlite';    

    % Create the test table
    eval_sqlite('CREATE TABLE Test(id INTEGER PRIMARY KEY, msg TEXT)')
    % Insert something simple
    eval_sqlite('INSERT INTO Test (msg) VALUES ("Hello World")');
    % Here we get a problem on linux
    txt = 'Ähm';
    eval_sqlite(['INSERT INTO Test (msg) VALUES ("', txt, '")']);

    function out = eval_sqlite(command)
        mksqlite( 'open', testDB );
        out = mksqlite( command );
        mksqlite( 'close' );
    end

end
```

I don't know much about mex files and c programming, however, it seems as if the error occurs somwhere around `line 253` in `mksqlite.cpp`

I would be really happy if you'd have an idea how this problem could be solved.
Thanks, Tobias

**Comment by VincentToups** [comment]
Hi DrTK.  I don't know that I can be much help as I no longer have a Matlab license to test with.  But this particular set of code I actually seem to have roped in from else where.  Looks like there is a repo of it here:

https://github.com/AndreasMartin72/mksqlite

Have you tried this version?  The maintainer might be able to help you more thoroughly than I can.

**Comment by DrTK** [comment]
Thanks for your reply. I contacted AndreasMartin72, and he confirmed the bug on linux. He has recently updated a debugged version, and now everything is running fine. 
In return, this means that your version still has a bug concerning writing utf8 encoded characters to sqlite database on linux.
I'm closing this issue. Thanks again.
